name: Build and Deploy
on: 
  workflow_dispatch
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v3
      - name: npm audit
        run: |
          npm ci
          npm audit --audit-level=moderate
      - name: Build image
        run: |
          docker build -t myapp:latest .
      - name: Scan image with Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          trivy image --exit-code 1 --severity CRITICAL myapp:latest
      - name: Sign in to Azure
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Push to ACR
        run: |
          az acr login -n sslablabacrels
          docker tag myapp:latest sslablabacrels.azurecr.io/myapp:latest
          docker push sslablabacrels.azurecr.io/myapp:latest
      - name: Deploy to WebApp
        run: |
          az webapp config container set \
          -g ss-lab-rg \
          -n sslab-webappels \
          --docker-custom-image-name sslablabacrels.azurecr.io/myapp:latest \
          --docker-registry-server-url https://sslablabacrels.azurecr.io \
          --docker-registry-server-user ${{secrets.ACR_USER}} \
          --docker-registry-server-password ${{secrets.ACR_PWD}}
